2017-11-29 00:01:20,305 [Thread-2:8888] [django.request:135] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, '/blog/index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-11-29 00:01:20,553 [Thread-3:7928] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, '/blog/index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-11-29 00:04:02,423 [Thread-2:7032] [django.request:135] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, '/blog/index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-11-29 00:04:02,617 [Thread-3:6812] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, '/blog/index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-11-29 00:04:25,604 [Thread-2:8368] [django.request:135] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 68, in render
    reraise(exc, self.backend)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: base.html
2017-11-29 00:04:25,867 [Thread-3:1944] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 68, in render
    reraise(exc, self.backend)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: base.html
2017-11-29 00:06:06,657 [Thread-2:8900] [django.request:135] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 68, in render
    reraise(exc, self.backend)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = self.nodelist.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 204, in render
    template = context.template.engine.get_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: blog/_paginator.html
2017-11-29 00:06:06,927 [Thread-3:1932] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 68, in render
    reraise(exc, self.backend)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = self.nodelist.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 204, in render
    template = context.template.engine.get_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: blog/_paginator.html
2017-11-29 00:27:26,089 [Thread-2:8712] [django.request:135] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 68, in render
    reraise(exc, self.backend)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: base.html
2017-11-29 00:27:26,325 [Thread-3:8720] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 68, in render
    reraise(exc, self.backend)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 148, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: base.html
2017-11-29 00:28:24,921 [Thread-2:8200] [django.request:135] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, '/blog/index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-11-29 00:28:25,153 [Thread-3:6048] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, '/blog/index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-11-29 08:07:11,717 [Thread-5:5284] [django.request:135] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, '/blog/index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-11-29 08:07:11,903 [Thread-6:5840] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, '/blog/index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-11-29 23:54:55,321 [Thread-50:7524] [django.request:135] [ERROR]- Internal Server Error: /index.html
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 17: 'static'. Did you forget to register or load this tag?
2017-11-29 23:54:55,615 [Thread-51:7532] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 571, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 17: 'static'. Did you forget to register or load this tag?
2017-11-30 00:04:28,733 [Thread-100:8520] [django.request:135] [ERROR]- Internal Server Error: /index.html
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '/img_5.jpg' from 'images/img_5.jpg'
2017-11-30 00:04:28,898 [Thread-101:7600] [django.request:135] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonWorkSpace\blog_project\blog\views.py", line 12, in index
    return render(request, 'index.html', locals())
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "F:\virtualenv\blog_project_venv\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '/img_5.jpg' from 'images/img_5.jpg'
